package demo23_注解;

/**
 * @author foyou
 * @version 1.1
 * @deprecated java注解学习，javadoc使用
 */
public class MyAnnotation {
    /**
     * Java文档小demo
     * @param message
     * @param size
     */
    public static void doc(String message,int size){
        //使用 javadoc 命令生成 使用注解标示信息 的帮助文档
//        >javadoc MyAnnotation.java
        //正在加载源文件MyAnnotation.java...
        //正在构造 Javadoc 信息...
        //标准 Doclet 版本 1.8.0_202-release
        //正在构建所有程序包和类的树...
        //正在生成.\demo23_注解\MyAnnotation.html...
        //MyAnnotation.java:11: 警告: @param 没有说明
        //     * @param message
        //       ^
        //MyAnnotation.java:12: 警告: @param 没有说明
        //     * @param size
        //       ^
        //正在生成.\demo23_注解\package-frame.html...
        //正在生成.\demo23_注解\package-summary.html...
        //正在生成.\demo23_注解\package-tree.html...
        //正在生成.\constant-values.html...
        //正在构建所有程序包和类的索引...
        //正在生成.\overview-tree.html...
        //正在生成.\index-all.html...
        //正在生成.\deprecated-list.html...
        //正在构建所有类的索引...
        //正在生成.\allclasses-frame.html...
        //正在生成.\allclasses-noframe.html...
        //正在生成.\index.html...
        //正在生成.\help-doc.html...
        //2 个警告
    }
}
